#!/usr/bin/env bash
#Run Nginx as Nginx
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i -e "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i -e "s/80/8080/g" /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
